### ISSUE TITLE
downloadResource() gets overwhelmed

### ISSUE THREAD

**Issue by kyleady** [kakaroto/R20Exporter#17]
R20Exporter sends out a flurry of requests to Roll20 on each step. If the campaign is large enough (as in my case) then network errors will start to pile up. The function `downloadResource()` will give up after the first network error, leading to a large number of missing blobs in the final ZIP file.

I solved this issue by adding in an exponential backoff to `downloadResource()`. However, this exponential backoff does not occur when receiving `404 Not Found` or `403 Forbidden`. I tested this out on an old campaign that had a large number of images that were added through the Roll20 search and Roll20 marketplace. The lack of retires when being hit with 403/404 kept the time to ZIP unaffected.

My modifications for adding the exponential backoff to `v0.7` can be found [here](https://github.com/kyleady/R20Exporter/commit/0a420349b8daec3003c3b578065e76fbfe70e9b6).

**Comment by kakaroto** [comment]
Why am I just seeing this now! 😭 I don't know why, but I didn't have this repo watched for some reason.
Thank you very much for the exponential backoff algo you added. I'll be merging that in soon!

**Comment by kakaroto** [comment]
This has **finally** been merged and released in 0.8.0. Thanks again and sorry for the delay!
