### ISSUE TITLE
Quotaexceedederror on export

### ISSUE THREAD

**Issue by Danishlion** [kakaroto/R20Exporter#18]
Hello I have a problem I hope you can help me with - when I try to export my campaign from roll20 (850 mb), i get a message saying quotaexceedederror when export is generating the .zip file:
"Error creating zip file writer: quotaexceedederror: The operation failed because it would cause the application to exceed its storage quota" Any way to fix this?
I appreciate any help!

**Comment by Danishlion** [comment]
Nevermind - fixed it by allowing app.roll20.net specifically for downloading local data in the Chrome browser and disabled clearing cache data and cookies on closing Chrome.

**Comment by stroup2202** [comment]
Thanks for sharing the fixes!

Note to others: do both fixes as just one will not sufficiently correct the issue.
