### ISSUE TITLE
Malformed lists in character bios

### ISSUE THREAD

**Issue by Spappz** [kakaroto/R20Exporter#19]
In a character's bio HTML, lists appear as a mix of roman and italic font with the odd asterisk at the end. Without trawling your code, my guess is that list bullets are converted to an asterisk ` * `, which is then parsed as markdown to produce HTML tags ` <em> `.

For example,
```
- abc def
- lmn opq
- uvw xyz
```
is converted to
```
<em> abc def </em> lmn opq * uvw xyz
```
(plus other `<p>` tags and whatnot). I should specify that this doesn't happen with all lists, but I can't confirm what exact stylistic differences cause it.

This is generally a bit messy to view outside R20, so if there's an easy fix it'd be appreciated!

**Comment by kakaroto** [comment]
There's no markdown/html conversion, the export puts the html as received by roll20 as is. So I'm finding this weird.
The converter also takes the html as is, so... I don't know how that would be changed. Can you check in the campaign.json file itself how the list appears from the raw exported html that Roll20 gives?

**Comment by Spappz** [comment]
Ah, I forgot about this!

Background was that I was helping a friend archive a mutual campaign, which contained a lot of 3rd-party D&D 5e material. The issue above was opened after I noticed the weird 'markdown-esque' entries in some characters' `bio.html`s. After cross-referencing some SRD characters (which didn't have the same issue) and talking to my friend a while later about it, it turned out that the content they wanted archived was... just like that. As in, in the bio, it displayed as
> _List item one_
> _List item two_
> *List item three

which, of course, got converted appropriately by R20E.

So, overall, the 3rd-party material that was being exported was just wonkily written into R20 itself, I didn't know at the time since my friend was the DM, and then I very handily forgot about making this issue.

Sorry for taking your time, and thanks for getting back about it!
