### ISSUE TITLE
Latest Download detects as infected

### ISSUE THREAD

**Issue by jbowensii** [kakaroto/R20Exporter#22]
With the latest BitDefender the latest download executable detects as infected by a virus.

**Comment by kakaroto** [comment]
That's a false positive which I unfortunately have no control over. If the 64 bit version isn't usable, then try the 32 bits version. I know that it will sometimes get flagged then that disappears after a BitDefender update, only to come back a few months later.
There's also a new update released yesterday, maybe give that a try and see if it's not getting flagged this time.
