### ISSUE TITLE
Launch world error after conversion

### ISSUE THREAD

**Issue by chrisjbrown** [kakaroto/R20Exporter#25]
After converting Curse of Strahd roll20 module. Launch world in Foundry. see error.

Foundry version: 0.7.9

![Screenshot 2021-03-13 100644](https://user-images.githubusercontent.com/1250638/111034484-e05df180-83e3-11eb-9341-510c303fdb93.jpg)

**Comment by kakaroto** [comment]
It most likely means that you didn't install the game system (dnd5e I suppose)? 
(Also note, this should be in https://github.com/kakaroto/R20Converter/issues as it has nothing to do with the exporter project itself)
I hope that helps.

**Comment by chrisjbrown** [comment]
yep you're right. 😅
