### ISSUE TITLE
Export Campaign button has disappeared

### ISSUE THREAD

**Issue by vRagnarockv** [kakaroto/R20Exporter#27]
![image](https://user-images.githubusercontent.com/97263968/148471094-c69aac83-8839-494a-8535-fa462b250b68.png)

The Export campaign button has disappeared from the My settings menu meaning I can longer export the campaign. Has this moved or is there an issue with it?

**Comment by kakaroto** [comment]
Thanks for creating the issue. I had just exported a campaign a couple of days ago and it was working fine, but it looks like Roll20 just changed their UI today, which broke it.
https://help.roll20.net/hc/en-us/articles/360037772613-Change-Log
![image](https://user-images.githubusercontent.com/27990/148471378-47eb025c-bc53-44d9-a4a8-5fa0d857fcee.png)

I'll work on this and release an update soon.

**Comment by kakaroto** [comment]
I've updated the README with instructions for a workaround : 
> press F12 in Chrome to open the devtools console, and type in it : `exporter.exportCampaignZip()` to start the export process manually.

**Comment by vRagnarockv** [comment]
Wow I didn't expect a workaround so fast thank you so much. All sorted and exported now, excellent work!

**Comment by kakaroto** [comment]
Updated version 0.8.0 (pending chrome store review) with the fix. Thanks!
