### ISSUE TITLE
Generation of zip file failed

### ISSUE THREAD

**Issue by spidey-ct** [kakaroto/R20Exporter#29]
The generation of the zip file failed due to low space on drive, and not being able to select a location with space.  
I am assuming, it is using C drive as default somewhere.  Small SSD on C, and storage on D. 
Is there an option to specify location so this will finish?

**Comment by kakaroto** [comment]
It uses the Chrome cache folder as that's the only thing available through the API. If you have a small SSD on C, you should configure your Windows to use D: drive for the user's `AppData` folder.
