### ISSUE TITLE
Character Files No Longer Have Detailed Data

### ISSUE THREAD

**Issue by bkvam** [kakaroto/R20Exporter#30]
I installed the extension a month or so ago and wrote a Perl script to extract the data from the character sheets in the downloaded .json file to display them in HTML format. It worked fine until today. It looks like the character details (skills, features, etc.) are no longer included in the downloaded .json when I export the campaign to .json file. The file I downloaded today is about 1.5M, and the previous file for the campaign was about 16M.

If I Export Campaign to a zip file instead the same problem occurs with the character.json files in the folders created for each character. In previous downloads they were about 60K, and now they're only about 4K.

Since the extension is unchanged, my guess is Roll20 changed something on their end that caused this to happen.

Anything you can do would be greatly appreciated.

**Comment by Aelanna64** [comment]
I have this same issue. I thought maybe I had an older version of the extension so removed and installed the newest one I could find. I exported the same campaign I had previously exported and the character files are all pretty much empty compared to the data I used to get. At the moment the extension doesn't really work.

**Comment by kakaroto** [comment]
Thanks for reporting the issue. It looks like Roll20 release an update yesterday which stopped automatically loading character sheet data on campaign load. I've published a fix and released it now. It should be available as soon as the Chrome Store finishes the review of the package (generally takes no more than a couple of hours).
**EDIT**: It's now published, only took 11 minutes for Chrome to review it :)

**Comment by ThiefMaster** [comment]
Could beyond20 for Firefox be updated as well? HP bars not updating is a bit annoying :D

**Comment by Amellwind** [comment]
I know its been a month since this was closed, but it looks like the converter is no longer extracting character sheet data again. It will grab the bio & info section fine, but not the actual stats. I thought to respond on this post before opening a new incident about the same issue.

**Comment by kakaroto** [comment]
> It will grab the bio & info section fine, but not the actual stats

I just gave it a try and it worked without issues. Are you sure that attributes are missing in the json?

**Comment by Amellwind** [comment]
> I just gave it a try and it worked without issues. Are you sure that attributes are missing in the json?

Well I apologize, I reinstalled VTT Enhancement Suite extension along with a few other tests after searching through earlier I saw everything but the stat block attributes, but they are there now. I don't know what I did but sorry for taking up your time.

**Comment by kakaroto** [comment]
No worries, it happens :) 
Enjoy!
