### ISSUE TITLE
Extension not visible on roll20

### ISSUE THREAD

**Issue by AkaiKoinzell** [kakaroto/R20Exporter#31]
Downloaded the extension on my chrome, but after accessing in my Roll20 game the ability to export in ZIP is not present:
![image](https://user-images.githubusercontent.com/96881015/168883331-e78c392d-ca8c-499e-93fd-47491bc12b7f.png)

**Comment by kakaroto** [comment]
It works for me : 
![image](https://user-images.githubusercontent.com/27990/168895412-2371c3de-505e-4758-9d38-bb620ed21d56.png)

Since the update to the roll20 settings menu, it doesn't show up as buttons at the top, but as its own entry at the bottom of the settings list.
