### ISSUE TITLE
Exporter Gets Stuck Saving Characters

### ISSUE THREAD

**Issue by DarthBinks93** [kakaroto/R20Exporter#35]
I believe this is a fairly large campaign, and every time I try to export it the exporter gets stuck here. 

![image](https://user-images.githubusercontent.com/15678333/229314198-e1243b23-62d2-45d9-a9ce-8bcb646cd2f9.png)

**Comment by kakaroto** [comment]
I think I've finally found the cause and fixed it. I just pushed an update to the extension to the chrome store and it should be available hopefully in the next hour or so.
Please try again once you see version 0.9.4 available and let me know if you still encoutner the issue.
Thanks!

**Comment by DarthBinks93** [comment]
No luck :(. 
![image](https://user-images.githubusercontent.com/15678333/229653720-5ddb356d-d466-4dc3-a3d6-119fb2ff244f.png)
![image](https://user-images.githubusercontent.com/15678333/229653762-cfc98682-544d-4740-9dd4-8c70ecefbbe6.png)

**Comment by kakaroto** [comment]
I finally managed to debug this with someone who had the issue who helped me gather more logs and test things until I got the proper fix! 
Version 0.9.5 which was just released should finally manage to get rid of this issue once and for all! Thanks for your patience and for reporting back.
Let me know if you experience any further issues with it. 
Thanks!

**Comment by DarthBinks93** [comment]
Fixed, thank you!!!!
