### ISSUE TITLE
Exporting to a ZIP file gets stuck at "Saving Journal handouts (5/10) 2 operations in progress.

### ISSUE THREAD

**Issue by MamuelSassey** [kakaroto/R20Exporter#36]
Hello! I am having a small issue, when exporting to a ZIP file it seems to get stuck at "Saving Journal handouts (5/10) 2 operations in progress." I am using Chrome and I have tried restarting the export, disabling all other extensions, clearing my cache and downloads, and clearing space on my C: drive. When I look at the log I see that there 4 separate logs reading "Can't find handout with ID: (4 separate ID strings for each one it cannot find)." Any tips on how to fix this? If I knew how to find handouts off of the IDs provided I would just manually export them and then delete them, but unfortunately I do not know how. Any help would be much appreciated! Thank you.

**Comment by kakaroto** [comment]
Hi!
Thanks for the chrome store review despite your issue! The "can't find handout with ID" isn't the cause of the issue, it just means that you had a handout that was deleted but the handout ID was still kept in roll20's "this is the order the handouts should appear in" (a roll20 bug, quite common).

I think I've finally found the cause of your specific stuck operation and fixed it. I just pushed an update to the extension to the chrome store and it should be available hopefully in the next hour or so.
Please try again once you see version 0.9.4 available and let me know if you still encounter the issue.
I hope it works, it's been a very hard bug to track down and fix!

Thanks!

**Comment by MamuelSassey** [comment]
Hello again! Thank you for getting back so quickly, you have amazing support! I really appreciate you working so hard to fix the issue. Unfortunately, I'm really sorry to say I am still having the same problem. If your able to help me still it would be much appreciate. Is there any further information I can provide to try to help?

**Comment by MamuelSassey** [comment]
(oops didn't mean to close)

**Comment by kakaroto** [comment]
Thanks for reporting back. It was indeed not completely fixed.
I finally managed to debug this with someone who had the issue who helped me gather more logs and test things until I got the proper fix! 
Version 0.9.5 which was just released should finally manage to get rid of this issue once and for all!
Let me know if you experience any further issues with it. 
Thanks!

**Comment by MamuelSassey** [comment]
It works now! Thank you so much for all your help!
