### ISSUE TITLE
R20Converter-0.12.1-win64 - no System assigned to pf1e converted world

### ISSUE THREAD

**Issue by Raezenkane** [kakaroto/R20Exporter#37]
I used the full zip export, then converted it.
When I try to launch the world, it can't launch - no game system.
When I edit the world, the system drop down is greyed out, so I can't change it.
How can I fix that?

**Comment by kakaroto** [comment]
Hi.
That means you need to install the game system in Foundry VTT. Go to the "systems" tab and install the game system (i.e: "DnD 5e").
I would also recommend you redo the conversion because the converter will be able to use the installed system to do a better job converting the campaign.
