### ISSUE TITLE
Does this (+R20 Converter) handle dynamic lightning

### ISSUE THREAD

**Issue by nicolasbraun** [kakaroto/R20Exporter#42]
Hello,

With R20 Subscription active will this also export / convert Dynamic Lightning ?
Thanks for everything,

Cheers

**Comment by kakaroto** [comment]
Hi,
Yes, it does convert dynamic lighting, though you don't need to have a Roll20 subscription for it to work.
Please watch this step by step guide, it should answer most of your questions:
https://www.youtube.com/watch?v=xAPS6NXZ0uM
I hope that helps.
