### ISSUE TITLE
Cannot read properties of undefined (reading 'slugify')

### ISSUE THREAD

**Issue by RememberMeFucker** [kakaroto/R20Exporter#45]
Error loading world "C:\Users\User\AppData\Local\FoundryVTT\Data\worlds\Test\world.json": Cannot read properties of undefined (reading 'slugify')

**Comment by kakaroto** [comment]
I don't know what that error is, but it's not related to R20Exporter. At best, it would be related to R20Converter, but it sounds more likely that it's a Foundry error, unrelated to any of those.
Without further information, it's impossible to tell.
