### ISSUE TITLE
Export stuck a 2/10 definitly

### ISSUE THREAD

**Issue by Kaelimh** [kakaroto/R20Exporter#47]
![image](https://github.com/user-attachments/assets/3b748d39-a3e1-4d60-91cb-59f1cad5f844)

Hi, i try to export my homebrew game from Roll20 to export it to my foundry server. It contains a lot of map.

But it stuck at 2/10 and stop doing anything else. I tried with another browser even on linux machine.

Do you need something for help youi to resolve this issue ?

Sorry for my bad english.

**Comment by kakaroto** [comment]
Hi,
I'm not sure what could cause it, as you're the only one with the issue. What browser are you using? Did you try a different one? It might have also been a temporary issue with roll20. Does it happen consistently?
I hope that helps

**Comment by fidl1** [comment]
hello
had the same issue, turns out its caused by the roll20 jumpgate beta
i returned to a previous version of my campaign which was before i switched to jumpgate and it downloaded properly
hope this helps somehow

**Comment by kakaroto** [comment]
> hello had the same issue, turns out its caused by the roll20 jumpgate beta i returned to a previous version of my campaign which was before i switched to jumpgate and it downloaded properly hope this helps somehow

Ah thanks! That's helpful, that should give me the ability to reproduce and fix it.
Would you mind sending me (in private) an invite link to the jumpgate game please? Thank you.

**Comment by Eronponce** [comment]
hi im facing the same problem :P

**Comment by kakaroto** [comment]
Thanks to @Eronponce, I was able to reproduce the issue and test my fixes. Turns out, I had already investigated this issue back in July (See #46) but never finished implementing the fix!
I've just made a new release with the fix, it's now pending review by the chrome store, it can take a few days for the review to complete and the update to be available.

**Comment by kakaroto** [comment]
Looks like they already approved the update. 
R20Exporter 0.10.0 should work: https://chromewebstore.google.com/detail/r20exporter/apbhfinbjilbkljgcnjjagecnciphnoi
(Note that if it's to use it with R20Converter, the converter doesn't yet support Jumpgate campaigns...)
